# This file was generated by GoReleaser. DO NOT EDIT.
cask "cadenya" do
  version "0.14.0"

  on_macos do
    on_intel do
      sha256 "8828a3ec3d915667e4cfb11b3a1252089ec10951d1b4d2a524f98b1d93521f6d"
      url "https://github.com/cadenya/cadenya-cli/releases/download/v#{version}/cadenya_#{version}_macos_amd64.zip"
    end
    on_arm do
      sha256 "2fb4341eeacc9f129a98204db59ee866627fcf0aca7187f275dc60719317b1f7"
      url "https://github.com/cadenya/cadenya-cli/releases/download/v#{version}/cadenya_#{version}_macos_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "d75cbce80cc5c540c11cebefbfdac8fddb82b3120d12d1ab9569c18ae61d0788"
      url "https://github.com/cadenya/cadenya-cli/releases/download/v#{version}/cadenya_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2af1488113b11f6b458db1236c8272c4cdb4b7b12e5ec653d766246c34205039"
      url "https://github.com/cadenya/cadenya-cli/releases/download/v#{version}/cadenya_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cadenya"
  desc "The official CLI for Cadenya."
  homepage "https://cadenya.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cadenya"
  manpage "man/man1/cadenya.1.gz"
  bash_completion "completions/cadenya.bash"
  fish_completion "completions/cadenya.fish"
  zsh_completion "completions/cadenya.zsh"

  # No zap stanza required

end
