# This file was generated by GoReleaser. DO NOT EDIT.
cask "cadenya" do
  version "0.12.0"

  on_macos do
    on_intel do
      sha256 "302eaf1d6852502bff8857a1188e857672fd1fda04b4b2d54c39b22e4f9ac8ea"
      url "https://github.com/cadenya/cadenya-cli/releases/download/v#{version}/cadenya_#{version}_macos_amd64.zip"
    end
    on_arm do
      sha256 "98fb95441f9588fdeed48141e655b9c8f1f7af011c5c1513e128e4db2e990434"
      url "https://github.com/cadenya/cadenya-cli/releases/download/v#{version}/cadenya_#{version}_macos_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "e75c39087641acc69184ec8a82af01503e02c6d376ca4ddbc73f718b3c105faa"
      url "https://github.com/cadenya/cadenya-cli/releases/download/v#{version}/cadenya_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0a6845adf64b6b1721f698df2d8af223535485a1a461ddd7ab9edbbdaf6b347e"
      url "https://github.com/cadenya/cadenya-cli/releases/download/v#{version}/cadenya_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cadenya"
  desc "The official CLI for Cadenya."
  homepage "https://cadenya.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cadenya"
  manpage "man/man1/cadenya.1.gz"
  bash_completion "completions/cadenya.bash"
  fish_completion "completions/cadenya.fish"
  zsh_completion "completions/cadenya.zsh"

  # No zap stanza required

end
