# This file was generated by GoReleaser. DO NOT EDIT.
cask "cadenya" do
  version "0.17.0"

  on_macos do
    on_intel do
      sha256 "99a42e9c15cb9f7c5cae4a7ecadc54dbb8c9a64e9dd4b6a80acbc2ea8eee2628"
      url "https://github.com/cadenya/cadenya-cli/releases/download/v#{version}/cadenya_#{version}_macos_amd64.zip"
    end
    on_arm do
      sha256 "bb1e6926c08bfd96cc6675255b61ad70d6eb32d8c643841155a322d13fc5dbf0"
      url "https://github.com/cadenya/cadenya-cli/releases/download/v#{version}/cadenya_#{version}_macos_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "001b9d9a4107acffbccb9bf3ec834b41fd07fa6e39169bbdaf512abda50df387"
      url "https://github.com/cadenya/cadenya-cli/releases/download/v#{version}/cadenya_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "164a96a3fad81580cea7a81cbbd05b5fbb25cdef4cbfae25cfb5995b55a82a23"
      url "https://github.com/cadenya/cadenya-cli/releases/download/v#{version}/cadenya_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cadenya"
  desc "The official CLI for Cadenya."
  homepage "https://cadenya.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cadenya"
  manpage "man/man1/cadenya.1.gz"
  bash_completion "completions/cadenya.bash"
  fish_completion "completions/cadenya.fish"
  zsh_completion "completions/cadenya.zsh"

  # No zap stanza required

end
