# This file was generated by GoReleaser. DO NOT EDIT.
cask "redwood" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "7bc30384fd86da7e22a74b5047f4d11a9fcc6b7abf0af9265a1b4d4887cafd96"
      url "https://github.com/cadenya/redwood/releases/download/v#{version}/redwood_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "98d5fc49764e2f550c3c76f22d2fcfc322c6141a71db70aa7ccf3ac7f06955f2"
      url "https://github.com/cadenya/redwood/releases/download/v#{version}/redwood_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1ad31c46084006b15afcc466d3abf738c083303aef5a10d269da9d479c3fe90f"
      url "https://github.com/cadenya/redwood/releases/download/v#{version}/redwood_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "64553d32ea6017f02b41dd7268172131b2a1880c9433baf377557affddc07e4b"
      url "https://github.com/cadenya/redwood/releases/download/v#{version}/redwood_#{version}_linux_amd64.tar.gz"
    end
  end

  name "redwood"
  desc "Statically typed SDK and CLI generator for OpenAPI"
  homepage "https://github.com/cadenya/redwood"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "redwood"

  # No zap stanza required
end
