# This file was generated by GoReleaser. DO NOT EDIT.
cask "redwood" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "c60a861dfd359afa61e7973e7b78cc7b31e076d57f8567e338b0ee0c67150fc4"
      url "https://github.com/cadenya/redwood/releases/download/v#{version}/redwood_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e72fbb9353926fb2f9c3b3457fb5bb9140df9a41cf02df9ffced390149834ffa"
      url "https://github.com/cadenya/redwood/releases/download/v#{version}/redwood_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "62cee5b47744e964adfb6d4b240c66fb25fac7db6a7fb48ac77e4c255a681dd7"
      url "https://github.com/cadenya/redwood/releases/download/v#{version}/redwood_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1b72adb0a00c5337f24a773f18a075bb4102583eb728f96824a1052b52b36509"
      url "https://github.com/cadenya/redwood/releases/download/v#{version}/redwood_#{version}_linux_amd64.tar.gz"
    end
  end

  name "redwood"
  desc "Statically typed SDK and CLI generator for OpenAPI"
  homepage "https://github.com/cadenya/redwood"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "redwood"

  # No zap stanza required
end
