# This file was generated by GoReleaser. DO NOT EDIT.
cask "redwood" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "fe9b7f5e37623d03d396e6d723710cd9bb11bd9b5aeaa2cdb282fbbf13ac59c3"
      url "https://github.com/cadenya/redwood/releases/download/v#{version}/redwood_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "128262c9814ef3514759e68cf983e7f0b4a2976bdeaafd11f19f5e05fd7d095a"
      url "https://github.com/cadenya/redwood/releases/download/v#{version}/redwood_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "97ead2de3050dda1871929ea843899314bf94a65838b0d21ef8cc0449d909890"
      url "https://github.com/cadenya/redwood/releases/download/v#{version}/redwood_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7c13df7b997e7d25c82a769e00b3d936f2520f5e9ac8dfd96bdde8b54413df7f"
      url "https://github.com/cadenya/redwood/releases/download/v#{version}/redwood_#{version}_linux_amd64.tar.gz"
    end
  end

  name "redwood"
  desc "Statically typed SDK and CLI generator for OpenAPI"
  homepage "https://github.com/cadenya/redwood"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "redwood"

  # No zap stanza required
end
